Implement migrations for RayyanStore reviews
rayyanqcri/rayyan-store pull request #110
Opened 2020-09-14 09:38 UTC by fabubaker

- Add script (scaffold-version.js) to generate migration skeleton.
- Use migrator to create and upgrade reviews.
- Setup tests using Jest.
- Add endpoint to get the version of a review.
- Modify createReview endpoint to accept version as a parameter.
- Update Ruby client to reflect API changes, bump version to 0.1.16

2020-09-14 18:55 UTC, hammady requested changes

2020-09-14 18:55 UTC, hammady commented on server/src/app.ts
> +  if (re.test(req.path)) {
We may support a `GET` request that matches this path in the future, which is neither `createReview` or `deleteReview`. I suggest explicitly checking for `POST` and `DELETE` methods to make it future-proof.

2020-09-14 18:55 UTC, hammady commented on server/src/app.ts
> +app.use(function (req, res, next) {
Does this middleware deserve to exist in its own file?

2020-09-14 18:55 UTC, hammady commented on server/src/app.ts
> +  let reviewId = req.query.review_id || req.body.review_id || _.last(req.url.split('/'))
I thought we now attach `reviewId` as an HTTP X-Header?
This will also ignore `createReview`?

2020-09-14 18:55 UTC, hammady commented on server/src/app.ts
> +      res.status(500).json({ error: err.message })
I am trying to think, is it safe to ignore the migration error and move on to the request as a best-effort approach? In some (most?) cases, the request will succeed, and if it fails, it was destined to fail anyway.

2020-09-14 18:55 UTC, hammady commented on server/src/adapters/postgres/migrations/20200906112019_create_initial_rayyan_store_tables.ts
> +    const queryText = `
I assumed this is a blind copy from the old file.

2020-09-14 18:55 UTC, hammady commented on server/src/adapters/postgres/migrator/base-migration.ts
> +export class BaseMigration {
Do we need a `downgrade` function?

2020-09-14 18:55 UTC, hammady commented on server/src/adapters/postgres/postgres.ts
> +      migrator.removeVersion(reviewId, client)
Do we also remove the version when soft deleting?

2020-09-15 05:35 UTC, fabubaker commented on server/src/adapters/postgres/migrations/index.ts
> +import { CreateInitialRayyanStoreTables } from './20200906112019_create_initial_rayyan_store_tables'
I adapted the Rails schema of naming migrations to the date that they were generated using the `scaffold-version` script. The format is `YYYYMMDDHHmmss`. 

Do you want me to change it to a linear versioning scheme?

2020-09-15 05:42 UTC, fabubaker commented on server/src/app.ts
> +app.use(function (req, res, next) {
Isn't moving it to its own file a bit much? What's the reasoning?

2020-09-15 05:48 UTC, fabubaker commented on server/src/app.ts
> +  let reviewId = req.query.review_id || req.body.review_id || _.last(req.url.split('/'))
`_.last(req.url.split('/')` takes care of createReview, but isn't `X-Review-ID` a rayyan-store-proxy detail? Although I do think it's easier to use than attempting to manually retrieve the reviewId here. 

I'll switch to `X-Review-ID`.

2020-09-15 05:50 UTC, fabubaker commented on server/src/adapters/postgres/migrations/20200906112019_create_initial_rayyan_store_tables.ts
> +    const queryText = `
Yep.

2020-09-15 05:54 UTC, fabubaker commented on server/src/adapters/postgres/postgres.ts
> +      migrator.removeVersion(reviewId, client)
Hmm, you're saying we should "soft-delete" the version as well?

2020-09-15 06:04 UTC, fabubaker commented on server/src/app.ts
> +      res.status(500).json({ error: err.message })
My worry with this is that it might lead to some data-integrity issues. I think it's best for migrations to fail fast and hard.

2020-09-15 11:27 UTC, hammady commented on server/src/adapters/postgres/migrations/index.ts
> +import { CreateInitialRayyanStoreTables } from './20200906112019_create_initial_rayyan_store_tables'
The rails schema is `date_random` to automate the sequence (the `date` part) and to guarantee uniqueness if 2 processes/developers created 2 migrations at the same second. If we are to follow this schema we should be aware that these are problems we need to fix. Yes, the `date` is the easiest way to automate the sequence and it will be cumbersome to generate unique sequences otherwise. Is there a way to have all zeros and not break this schema? Do you verify it somewhere?

2020-09-15 11:29 UTC, hammady commented on server/src/app.ts
> +app.use(function (req, res, next) {
Typically middlewares are best maintained in their own files, but this one might be too small to qualify. I'm only drawing your attention to this possibility. Don't do if you see it an overkill.

2020-09-15 11:31 UTC, hammady commented on server/src/app.ts
> +  let reviewId = req.query.review_id || req.body.review_id || _.last(req.url.split('/'))
No it is not an RSP detail, it is a client specification as exposed by the gem. RSP only consumes it and RS can do this too.

2020-09-15 11:34 UTC, hammady commented on server/src/app.ts
> +      res.status(500).json({ error: err.message })
That might be true. But I cannot overlook the situation where we would have a bug in migrations that will fail the majority of requests where they would normally succeed without attempting migrations.

2020-09-15 11:35 UTC, hammady commented on server/src/adapters/postgres/migrator/base-migration.ts
> +export class BaseMigration {
Before rushing into the implementation, do we need it now? How would we invoke it?

2020-09-15 11:37 UTC, hammady commented on server/src/adapters/postgres/postgres.ts
> +      migrator.removeVersion(reviewId, client)
Yes, because not doing so will leave the soft-deleted review in an incomplete state (you don't know what version it corresponds to). So either soft-delete the version as well (add a boolean: deleted), or don't delete it at all, what is the impact of leaving it? It would be hard to clean it I guess.

2020-09-15 12:33 UTC, fabubaker commented on server/src/adapters/postgres/migrator/base-migration.ts
> +export class BaseMigration {
We don't need it now but it might be better to have downgrade functions ready in case we do need them in the future. Although I can't think of a scenario where we would need them...

2020-09-15 12:42 UTC, fabubaker commented on server/src/adapters/postgres/migrations/index.ts
> +import { CreateInitialRayyanStoreTables } from './20200906112019_create_initial_rayyan_store_tables'
I guess technically you could have the base version be all zeroes and it would still work with the migrator as it is. See the table definition, for eg:

```
CREATE TABLE IF NOT EXISTS review_versions (
        review_id INTEGER PRIMARY KEY,
        version BIGINT CHECK (version >= 0)
      )
```

I can change it to `0000000000000_create_initial_rs_tables`, but we are sticking to the date as the migration sequence yes?

2020-09-15 12:53 UTC, fabubaker commented on server/src/adapters/postgres/scripts/scaffold-version.js
> +#!/usr/bin/env node
Done, I added a `server` section to the readme.

2020-09-15 12:53 UTC, fabubaker commented on server/src/app.ts
> +  if (re.test(req.path)) {
Done.

2020-09-15 13:14 UTC, fabubaker commented on server/src/app.ts
> +      res.status(500).json({ error: err.message })
Isn't that what tests and staging is for? :)

2020-09-15 15:02 UTC, fabubaker commented on server/src/adapters/postgres/postgres.ts
> +      migrator.removeVersion(reviewId, client)
The problem is that there can be multiple soft-deleted versions of the same review, so we may need a separate table for them.

Is soft-deleting even useful anymore? I'm in favor of getting rid of it.

2020-09-16 08:42 UTC, hammady commented on server/src/adapters/postgres/migrations/index.ts
> +import { CreateInitialRayyanStoreTables } from './20200906112019_create_initial_rayyan_store_tables'
Yes. Please go ahead.

2020-09-16 08:44 UTC, hammady commented on server/src/adapters/postgres/scripts/scaffold-version.js
> +#!/usr/bin/env node
In the new section, you specified `npm` as the migration command and `docker-compose` as the test runner. Either use compose in all or none.

2020-09-16 08:45 UTC, hammady commented on server/src/app.ts
> +      res.status(500).json({ error: err.message })
Yes, but only if we guarantee bugs do not show up later in some edge cases!

2020-09-16 08:46 UTC, hammady commented on server/src/adapters/postgres/migrator/base-migration.ts
> +export class BaseMigration {
Isn't deleting a review a downgrade of version 0? Can you implement it as such?

2020-09-16 08:47 UTC, hammady commented on server/src/adapters/postgres/postgres.ts
> +      migrator.removeVersion(reviewId, client)
OK, get rid of it. Later we can automatically archive reviews before deletion (could be out of scope of rayyan-store, but its clients).

2020-09-16 08:48 UTC, hammady commented on server/src/adapters/postgres/migrations/index.ts
> +import { CreateInitialRayyanStoreTables } from './00000000000000_create_initial_rayyan_store_tables'
This looks very neat to my eyes now!

2020-09-16 10:32 UTC, fabubaker commented on server/src/adapters/postgres/migrator/base-migration.ts
> +export class BaseMigration {
I thought about initially implementing `deleteReview` as a series of cascaded downgrades, but it's just simpler to drop the tables.

I propose not having a downgrade for version 0 (maybe have it throw an error), and then I can have downgrades for all the other versions, if we ever happen to need them.

2020-09-17 12:21 UTC, fabubaker commented on server/src/adapters/postgres/scripts/scaffold-version.js
> +#!/usr/bin/env node
Done.

2020-09-17 12:21 UTC, fabubaker commented on server/src/adapters/postgres/postgres.ts
> +      migrator.removeVersion(reviewId, client)
Removed.

2020-09-17 16:05 UTC, hammady commented on README.md
> +docker-compose run --rm -v $PWD:/home server npm run migrator:scaffold "<title of migration>"
Why not declare the volume inside the `docker-compose.yaml`? We are getting rid of compose soon anyway, so this is optional if it takes more than a minute.

2020-09-20 11:14 UTC, fabubaker commented on README.md
> +docker-compose run --rm -v $PWD:/home server npm run migrator:scaffold "<title of migration>"
Done

2020-09-24 14:20 UTC, hammady commented on server/src/app.ts
> +      res.status(500).json({ error: err.message })
Agreed to fail early.

2020-09-24 14:21 UTC, hammady commented on server/src/adapters/postgres/migrator/base-migration.ts
> +export class BaseMigration {
Agreed that it is simpler to delete reviews explicitly instead of undoing all migrations one by one.

2020-09-24 14:21 UTC, hammady approved these changes

2020-09-24 14:22 UTC, hammady reviewed
Any endpoint to invoke a downgrade?

2020-09-27 15:43 UTC, fabubaker commented
> Any endpoint to invoke a downgrade?

Yep, done.

2020-09-28 07:30 UTC, hammady commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
What happens if there is another request targeting the same review which will try to upgrade in the same time? If we lock the tables, the upgrade will be sequenced, then what is the benefit of downgrade?

2020-09-28 07:30 UTC, hammady commented on server/src/app.ts
> +app.post('/reviews/:review_id/downgrade', (req, res) => {
Will this request skip the upgrade middleware?

2020-09-28 07:51 UTC, fabubaker commented on server/src/app.ts
> +app.post('/reviews/:review_id/downgrade', (req, res) => {
Good catch, I should also disable it for the `getReviewVersion` endpoint.

2020-09-28 08:05 UTC, fabubaker commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
It will be useful in scenarios where the latest migration has to be withdrawn and all reviews have to be dowgraded to an older version.

2020-09-28 08:34 UTC, hammady commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
In which case, we have to change the latest version back to prevent further upgrades, then we launch downgrades. Does this mean the race condition I mentioned above cannot happen?

2020-09-28 08:36 UTC, hammady commented on server/src/app.ts
>    // Exclude createReview and deleteReview from auto-migrations
If this covers downgrades and getVersion, then let's document it here.

2020-09-28 08:47 UTC, fabubaker commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
Assuming we change the latest version back, any attempt to perform an automatic upgrade will fail (because `upgradeVersion < currentVersion`). So only the downgrade will go through.

2020-09-28 09:08 UTC, hammady commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
Why does it imply removing the migration itself? In case of rollback, we just change the latest version and keep the migrations so that downgrades work. Would that work?

2020-09-28 09:37 UTC, fabubaker commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
The latest version is automatically obtained from the sorted list of versions:
```
this.latestVersion = this.versions[this.versions.length - 1]
```

So the only way to change the latest version is to not export it from the `migrations` folder.

2020-09-28 10:47 UTC, hammady commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
I thought we explicitly set a variable for the last version. This gives more flexibility but any new migration PR should also update this variable (or the generator script).

2020-09-28 12:47 UTC, fabubaker commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
How about something like:

```
this.latestVersion = parseInt(process.env.LATEST_MIGRATION_VERSION || this.versions[this.versions.length - 1])
```

So if it's not specified, the latest version defaults to the last version in the list.

2020-09-28 16:10 UTC, fabubaker commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
Helm overrides should be good no?

2020-09-29 10:41 UTC, hammady commented on server/src/adapters/postgres/migrator/migrator.ts
> +  async downgrade(reviewId: number, downgradeVersion: number): Promise<any> {
I thought you will always set the latest version and every migration class generator should also change it. This is as asking the developer go check the migrations folder to determine the latest instead of looking at a number in the same file. Anyway, it servers the purpose.

2020-09-29 10:42 UTC, hammady approved these changes

2020-09-30 05:54 UTC, merged