Add helm chart and skaffold manifest
rayyanqcri/rayyan-store pull request #111
Opened 2020-09-21 17:07 UTC by fabubaker

2020-09-22 07:15 UTC, fabubaker commented on server/helm/rayyan-store/Chart.yaml
> +- name: rayyanlib
Don't think rayyan-store needs rayyanlib. Should I remove it?

2020-09-22 07:22 UTC, hammady commented on server/helm/rayyan-store/Chart.yaml
> +- name: rayyanlib
Remove it if not used. I think rayyan-store has its own templates already.

2020-09-22 13:47 UTC, hammady requested changes

2020-09-22 13:47 UTC, hammady commented on README.md
> +## Build and Run
You need `rayyancore` for the image pull secrets and newrelic-license secret.

2020-09-22 13:47 UTC, hammady commented on server/helm/rayyan-store/templates/deployments/rayyan-store.yaml
> +    rayyan.store.backend: rayyan-store {{- $index }}
It is better to use the label selectors from the helpers to attach the chart version and trigger a rolling update on releases. See https://github.com/rayyanqcri/rayyan-cloud/pull/71/commits/c8233303f50b1211588f8cb5283c27488f360ba1.

2020-09-22 13:47 UTC, hammady commented on server/helm/rayyan-store/value-overrides/local.yaml
> +  RAYYAN_STORE_DATABASE_URLS: [DUMMY]
Better write in native YAML?
```suggestion
  RAYYAN_STORE_DATABASE_URLS:
  - DUMMY
```

2020-09-22 13:47 UTC, hammady commented on server/helm/rayyan-store/value-overrides/staging.yaml
> +  resources:
I know this is inherited as is, but I didn't know we are giving staging that much resources!

2020-09-22 13:47 UTC, hammady commented on server/helm/rayyan-store/values.yaml
> +rayyanStore:
All values here (except `backends`) are duplicated in both staging and prod in `values-overrides` unnecessarily.

2020-09-22 13:47 UTC, hammady commented on skaffold.yaml
> +    path: /build/artifacts/0/docker
```suggestion
    path: /build/artifacts/0/docker/dockerfile
```

2020-09-22 13:47 UTC, hammady commented on skaffold.yaml
> +      dockerfile: Dockerfile
```suggestion
    value: Dockerfile
```
This is more explicit than replacing the whole block (we may add other options later).

2020-09-22 14:15 UTC, hammady requested changes

2020-09-22 14:15 UTC, hammady commented on server/helm/rayyan-store/value-overrides/staging.yaml
> +  replicas: 1
This can be the default.

2020-09-22 14:15 UTC, hammady commented on server/helm/rayyan-store/values.yaml
> +  backends: [0]
An empty ` secrets: {} ` is necessary so that the chart can be deployed without any overrides.

2020-09-22 14:15 UTC, hammady commented on server/helm/rayyan-store/templates/secrets/rayyan-store.yaml
> +{{- range $index, $url := .Values.secrets.RAYYAN_STORE_DATABASE_URLS }}
Now you can de-scope the secret name (no more monolith chart):
```suggestion
{{- range $index, $url := .Values.secrets.DATABASE_URLS }}
```

2020-09-22 17:14 UTC, fabubaker commented on skaffold.yaml
> +    path: /build/artifacts/0/docker
Wait, I don't understand, why do we need this change?

2020-09-22 17:44 UTC, fabubaker commented on server/helm/rayyan-store/templates/deployments/rayyan-store.yaml
> +    rayyan.store.backend: rayyan-store {{- $index }}
The helpers defines `app.kubernetes.io/name: {{ include "rayyan-store.name" . }}`, but in the deployment we have `app.kubernetes.io/name: rayyan-store {{- $index }}`. where `index` is the index of the backend.

How do I resolve this conflict? I was thinking of removing `app.kubernetes.io/name` from `helpers.tpl`.

2020-09-22 17:46 UTC, fabubaker commented on README.md
> +## Build and Run
Done.

2020-09-22 17:47 UTC, fabubaker commented on server/helm/rayyan-store/value-overrides/staging.yaml
> +  resources:
I reduced cpu to 100m, should be good right?

2020-09-23 06:29 UTC, fabubaker commented on server/helm/rayyan-store/templates/deployments/rayyan-store.yaml
> +{{- range $index, $backend := $rayyanStore.backends }}
So I was thinking rather than iterating through `$rayyanStore.backends`, why not just directly iterate through `Values.secrets.DATABASE_URLS`? 

This would get rid of having to maintain a separate `backends` key.

2020-09-23 06:37 UTC, hammady commented on server/helm/rayyan-store/templates/deployments/rayyan-store.yaml
> +    rayyan.store.backend: rayyan-store {{- $index }}
You can address this the same way [rayyanlib 1.0.0](https://github.com/rayyanqcri/rayyan-cloud/pull/73/commits/9072671b0b8a05b3904e689dc84066972aa41cfd) addresses it. `app.kubernetes.io/name` is not part of the selectors.

2020-09-23 06:40 UTC, hammady commented on server/helm/rayyan-store/templates/deployments/rayyan-store.yaml
> +{{- range $index, $backend := $rayyanStore.backends }}
Sure.

2020-09-23 06:50 UTC, hammady commented on server/helm/rayyan-store/value-overrides/staging.yaml
> +  resources:
What does NR say?

2020-09-23 06:51 UTC, hammady commented on server/helm/rayyan-store/value-overrides/staging.yaml
> +    NODEPG_DEBUG: 1
You can move common env values in `values.yaml`.

2020-09-23 06:52 UTC, hammady commented on server/helm/rayyan-store/value-overrides/prod.yaml
> +      cpu: 500m
What does NR say here too?

2020-09-23 08:02 UTC, fabubaker commented on server/helm/rayyan-store/value-overrides/staging.yaml
> +  resources:
NR says this:
![image](https://user-images.githubusercontent.com/9405286/93983865-c7a54500-fd8b-11ea-94d5-b19fcb85a77c.png)

Note that I've kept the 500m cpu for prod, the 100m is for local and staging only.

2020-09-23 08:23 UTC, fabubaker commented on server/helm/rayyan-store/value-overrides/prod.yaml
> +      cpu: 500m
See https://github.com/rayyanqcri/rayyan-store/pull/111#discussion_r493282474.

2020-09-23 08:23 UTC, fabubaker commented on server/helm/rayyan-store/value-overrides/staging.yaml
> +    NODEPG_DEBUG: 1
Done.

2020-09-23 11:10 UTC, hammady requested changes

2020-09-23 11:10 UTC, hammady commented on server/helm/rayyan-store/templates/deployments/rayyan-store.yaml
> +      {{- include "rayyan-store.selectorLabels" $root | nindent 4 }}
```suggestion
      {{- include "rayyan-store.selectorLabels" $root | nindent 6 }}
```

2020-09-23 11:10 UTC, hammady commented on server/helm/rayyan-store/templates/deployments/rayyan-store.yaml
> +        {{- include "rayyan-store.labels" $root | nindent 4 }}
```suggestion
        {{- include "rayyan-store.labels" $root | nindent 8 }}
```

2020-09-23 11:12 UTC, hammady commented on server/helm/rayyan-store/value-overrides/prod.yaml
> +      cpu: 500m
Isn't the screenshot for staging? If prod also needs 1% only, we are giving it half a core (50%)?

2020-09-23 11:19 UTC, fabubaker commented on server/helm/rayyan-store/value-overrides/prod.yaml
> +      cpu: 500m
The screenshot was from prod, but you're right. I'll decrease prod cpu to 100m as well.

2020-09-23 11:51 UTC, hammady approved these changes

2020-09-23 11:54 UTC, merged